cmake_minimum_required(VERSION 3.12)

if(NOT DEFINED RETROFE_VERSION_SOURCE_DIR)
    get_filename_component(RETROFE_VERSION_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/../Source" ABSOLUTE)
endif()
if(NOT DEFINED RETROFE_VERSION_BINARY_DIR)
    set(RETROFE_VERSION_BINARY_DIR "${CMAKE_BINARY_DIR}")
endif()

# Source archives may have Git installed without containing a repository.
set(GIT_COMMIT_NO "0")
set(GIT_SHORT_HASH "0")
set(RETROFE_WC_BRANCH "Outside Git")
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --show-toplevel
        WORKING_DIRECTORY "${RETROFE_VERSION_SOURCE_DIR}"
        RESULT_VARIABLE GIT_REPOSITORY_RESULT
        OUTPUT_QUIET
        ERROR_QUIET
    )
    if(GIT_REPOSITORY_RESULT EQUAL 0)
        execute_process(
            COMMAND "${GIT_EXECUTABLE}" rev-list --count HEAD
            WORKING_DIRECTORY "${RETROFE_VERSION_SOURCE_DIR}"
            RESULT_VARIABLE GIT_COUNT_RESULT
            OUTPUT_VARIABLE GIT_COUNT_OUTPUT
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
        )
        execute_process(
            COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
            WORKING_DIRECTORY "${RETROFE_VERSION_SOURCE_DIR}"
            RESULT_VARIABLE GIT_HASH_RESULT
            OUTPUT_VARIABLE GIT_HASH_OUTPUT
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
        )
        execute_process(
            COMMAND "${GIT_EXECUTABLE}" rev-parse --abbrev-ref HEAD
            WORKING_DIRECTORY "${RETROFE_VERSION_SOURCE_DIR}"
            RESULT_VARIABLE GIT_BRANCH_RESULT
            OUTPUT_VARIABLE GIT_BRANCH_OUTPUT
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
        )
        if(GIT_COUNT_RESULT EQUAL 0 AND GIT_HASH_RESULT EQUAL 0 AND GIT_BRANCH_RESULT EQUAL 0)
            set(GIT_COMMIT_NO "${GIT_COUNT_OUTPUT}")
            set(GIT_SHORT_HASH "${GIT_HASH_OUTPUT}")
            set(RETROFE_WC_BRANCH "${GIT_BRANCH_OUTPUT}")
        endif()
    endif()
endif()

string(TIMESTAMP RETROFE_BUILD_DATE "%Y-%m-%d" UTC)

set(RETROFE_VERSION_MAJOR "2504")
set(RETROFE_VERSION_MINOR "2")
set(RETROFE_VERSION_PATCH "${GIT_SHORT_HASH}")
set(RETROFE_VERSION_GITNO "${GIT_COMMIT_NO}")

if(RETROFE_WC_BRANCH STREQUAL "master")
    set(RETROFE_WC_BRANCH "")
endif()

set(RETROFE_VERSION_DESCRIBE "${RETROFE_VERSION_MAJOR}.${RETROFE_VERSION_MINOR}")

set(VERSION_HEADER "${RETROFE_VERSION_BINARY_DIR}/autogen/versioning.h")
file(WRITE "${VERSION_HEADER}" "// Auto-generated versioning header\n")
file(APPEND "${VERSION_HEADER}" "#ifndef VERSIONING_H\n#define VERSIONING_H\n\n")
file(APPEND "${VERSION_HEADER}" "#define RETROFE_VERSION_MAJOR \"${RETROFE_VERSION_MAJOR}\"\n")
file(APPEND "${VERSION_HEADER}" "#define RETROFE_VERSION_MINOR \"${RETROFE_VERSION_MINOR}\"\n")
file(APPEND "${VERSION_HEADER}" "#define RETROFE_VERSION_PATCH \"${RETROFE_VERSION_PATCH}\"\n")
file(APPEND "${VERSION_HEADER}" "#define RETROFE_VERSION_GITNO \"${RETROFE_VERSION_GITNO}\"\n")
file(APPEND "${VERSION_HEADER}" "#define RETROFE_VERSION_DESCRIBE \"${RETROFE_VERSION_DESCRIBE}\"\n")
file(APPEND "${VERSION_HEADER}" "#define RETROFE_WC_BRANCH \"${RETROFE_WC_BRANCH}\"\n")
file(APPEND "${VERSION_HEADER}" "#define RETROFE_BUILD_DATE \"${RETROFE_BUILD_DATE}\"\n\n")
file(APPEND "${VERSION_HEADER}" "#endif // VERSIONING_H\n")
