name: Windows exe's
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    name: Build Windows

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - name: Install dependencies
        run: |
          choco install -y gstreamer
          choco install -y gstreamer-devel

      - name: Configure environment
        run: |
          cmake -A x64 -B .\RetroFE\Build -D GSTREAMER_ROOT=D:\gstreamer\1.0\msvc_x86_64 -S .\RetroFE\Source
  
      - name: Build RetroFE
        run: |
          cmake --build RetroFE/Build --config Release

      - name: Copy DLLs and prepare package
        run: |
          mkdir .\RetroFE\Build\Release\retrofe
          xcopy /S /I /Y .\Package\Environment\Windows\retrofe .\RetroFE\Build\Release\retrofe
          move .\RetroFE\Build\Release\retrofe.exe .\RetroFE\Build\Release\retrofe\retrofe.exe
          copy .\Package\Environment\Windows\RetroFE.lnk .\RetroFE\Build\Release

      - name: Upload retrofe.exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: retrofe.exe
          path: |
            D:\a\RetroFE\RetroFE\RetroFE\Build\Release\retrofe
            D:\a\RetroFE\RetroFE\RetroFE\Build\Release\RetroFE.lnk

