name: RetroFE Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Cache apt dependencies
    - name: Cache apt dependencies
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          g++ \
          cmake \
          dos2unix \
          zlib1g-dev \
          libsdl2-2.0-0 \
          libsdl2-mixer-2.0-0 \
          libsdl2-image-2.0-0 \
          libsdl2-ttf-2.0-0 \
          libsdl2-dev \
          libsdl2-mixer-dev \
          libsdl2-image-dev \
          libsdl2-ttf-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer-plugins-good1.0-dev \
          gstreamer1.0-libav \
          libglib2.0-0 \
          libglib2.0-dev \
          sqlite3 \
          libevdev-dev \
          libminizip-dev \
          libusb-1.0-0-dev

    # Configure the build
    - name: Configure CMake
      run: cmake RetroFE/Source -BRetroFE/Build

    # Build the project
    - name: Build
      run: cmake --build RetroFE/Build
