name: Linux AppImages

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        config:
          - { os: ubuntu-24.04, arch: x86_64 }
          - { os: ubuntu-24.04-arm, arch: arm64 }
          - { os: ubuntu-22.04-arm, arch: arm64 } # Raspberry Pi OS Target
    runs-on: ${{ matrix.config.os }}
    name: Build ${{ matrix.config.arch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            cmake 
            dos2unix 
            zlib1g-dev
            libsdl2-2.0 
            libsdl2-mixer-2.0
            libsdl2-image-2.0 
            libsdl2-ttf-2.0
            libsdl2-dev 
            libsdl2-mixer-dev 
            libsdl2-image-dev 
            libsdl2-ttf-dev
            libgstreamer1.0 
            libgstreamer1.0-dev 
            libgstreamer-plugins-base1.0-dev
            gstreamer1.0-plugins-base 
            gstreamer1.0-plugins-good
            gstreamer1.0-libav
            libglib2.0-0 
            libglib2.0-dev 
            sqlite3 
            libminizip-dev 
            libwebp-dev 
            libusb-1.0-0
            libusb-1.0-0-dev
            libevdev-dev
          version: ${{ matrix.config.os }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake dos2unix zlib1g-dev libunwind-dev \
                                  libsdl2-2.0 libsdl2-mixer-2.0 libsdl2-image-2.0 libsdl2-ttf-2.0 \
                                  libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-ttf-dev \
                                  libgstreamer1.0 libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
                                  gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-libav \
                                  libglib2.0-0 libglib2.0-dev sqlite3 libminizip-dev libwebp-dev libusb-1.0-0 libusb-1.0-0-dev libevdev-dev 
                                  

      - name: Configure CMake
        run: cmake RetroFE/Source -BRetroFE/Build

      - name: Build
        run: cmake --build RetroFE/Build

      - name: Install linuxdeploy
        run: |
          if [ "${{ matrix.config.arch }}" == "arm64" ]; then
            wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-aarch64.AppImage -O linuxdeploy-arm64.AppImage
            chmod +x linuxdeploy-arm64.AppImage
          else
            wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-${{ matrix.config.arch }}.AppImage
            chmod +x linuxdeploy-${{ matrix.config.arch }}.AppImage
          fi
          
      - name: Install linuxdeploy-plugin-gstreamer
        run: |
          wget https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gstreamer/refs/heads/master/linuxdeploy-plugin-gstreamer.sh
          chmod +x linuxdeploy-plugin-gstreamer.sh

      - name: Package AppImage
        run: |
          ./linuxdeploy-${{ matrix.config.arch }}.AppImage \
            --executable RetroFE/Build/retrofe \
            --appdir RetroFE/Build/AppDir \
            --plugin gstreamer \
            --output appimage \
            --desktop-file Package/Environment/Linux/retrofe.desktop \
            --icon-file Package/Environment/Common/RetroFE.png
          if [ "${{ matrix.config.arch }}" == "arm64" ]; then
            if [ "${{ matrix.config.os }}" == "ubuntu-24.04-arm" ]; then
              mv RetroFE-aarch64.AppImage RetroFE-arm64.AppImage
            elif [ "${{ matrix.config.os }}" == "ubuntu-22.04-arm" ]; then
              mv RetroFE-aarch64.AppImage RetroFE-raspi.AppImage
            fi
          fi
    
      - name: Upload ARM64 AppImage
        if: ${{ matrix.config.arch == 'arm64' && matrix.config.os == 'ubuntu-24.04-arm' }}
        uses: actions/upload-artifact@v4
        with:
          name: RetroFE-arm64.AppImage
          path: RetroFE-arm64.AppImage
      
      - name: Upload Raspi AppImage
        if: ${{ matrix.config.arch == 'arm64' && matrix.config.os == 'ubuntu-22.04-arm' }}
        uses: actions/upload-artifact@v4
        with:
          name: RetroFE-raspi.AppImage
          path: RetroFE-raspi.AppImage
      
      - name: Upload Other Arch AppImage
        if: ${{ matrix.config.arch != 'arm64' }}
        uses: actions/upload-artifact@v4
        with:
          name: RetroFE-${{ matrix.config.arch }}.AppImage
          path: RetroFE-${{ matrix.config.arch }}.AppImage
