name: Windows exe's
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    name: Build Windows

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - name: Install dependencies
        run: |
          choco install -y gstreamer

      - name: Configure environment
        run: |
          cmake -A x64 -B .\RetroFE\Build -D GSTREAMER_ROOT=C:\gstreamer\1.0\msvc_x86_64 -S .\RetroFE\Source
  
      - name: Build RetroFE
        run: |
          cmake --build RetroFE/Build --config Release
