name: Sync Docs to Wiki

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Clone Wiki repository
        run: |
          git clone https://github.com/${{ github.repository }}.wiki.git wiki

      - name: Sync docs to Wiki
        run: |
          rsync -av --delete docs/ wiki/
          cd wiki
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Sync docs to Wiki"
          git push
